### ISSUE TITLE
Code of Average Precision

### ISSUE THREAD

**Issue by prakhar123pradhan** [qinnzou/DeepCrack#10]
Hello Sir!
Thank you for providing the code. Can you please also provide the code to calculate the Average Precision (area under P-R curve). I have the predicted segmented mask and the ground-truth.

**Comment by zhuhaonan** [comment]
I have same problem

**Comment by qinnzou** [comment]
The precision-recall results can be calculated by using  the edge detection benchmark of Berkeley. The codes can be found at  https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/bsds/
