### ISSUE TITLE
two questions for training step

### ISSUE THREAD

**Issue by Marmar202** [qinnzou/DeepCrack#11]
I wanted to run your code and then after that modify it to pursue my project objectives. 
At the training step, you had written "Before training, change the paths including "train_path"(for train_index.txt), "pretrained_path" in config.py to adapt to your environment." I can't find them in the config.py,  where do you mean here to change the paths?
my second question is about the datasets, I downloaded them but I don't know where to locate them? in the "Data" folder?

thanks for your response in advance

**Comment by Dhuzi96** [comment]
你解决了吗兄弟？

**Comment by Dhuzi96** [comment]
你解决了吗兄弟？

**Comment by dys-c** [comment]
1. # path

    test_data_path = 'data/test_example.txt'
    train_data_path = 'data/train_example.txt'
    val_data_path = 'data/val_example.txt'
    checkpoint_path = 'DeepCrack_CT260_FT1.pth'

2.After you download the data such as CT260,place those four packages under the code folder and use the CT file as the train dataset. The author of this part has explained other questions

**Comment by qinnzou** [comment]
@dys-c thanks
