### ISSUE TITLE
您好，请问可以提供测试集上的结果吗

### ISSUE THREAD

**Issue by zhuhaonan** [qinnzou/DeepCrack#12]
我们也在做相关的研究，您给的预训练模型无法达到您的最佳结果。所以我们希望可以获得你们在测试集上的最佳结果用于方法之间的对比。谢谢。

**Comment by Dhuzi96** [comment]
> ，您给的预训练模型无法达到您的最佳结果。所以我们希望可

请问您他这个ODS/OIS还有PR曲线的代码在哪里能看到啊

**Comment by Dhuzi96** [comment]
作者的代码需要对输入图片的大小有要求吗

**Comment by chenghd98** [comment]
模型巨难训练啊  2000张图片  训练1epoch要1小时了

**Comment by qinnzou** [comment]
Yes. @zhuhaonan We will release the test results. @chenghd98 I did not know what GPU you used. The running speed reported in our paper is based on two TiTAN.
