### ISSUE TITLE
model is missing 

### ISSUE THREAD

**Issue by nvnnghia** [qinnzou/DeepCrack#2]
Thanks for sharing your great work. Can you update the content inside model/? And if possible please upload the pretrained weights to google drive or another place, because I can not access baidu server. Thank you

**Comment by qinnzou** [comment]
> Thanks for sharing your great work. Can you update the content inside model/? And if possible please upload the pretrained weights to google drive or another place, because I can not access baidu server. Thank you

Thanks for your reminder. I have uploaded the model file. The pretrained model is shared through google drive now. Any problem please contact me. Thanks.

**Comment by nvnnghia** [comment]
Awesome. Thank you very much
