### ISSUE TITLE
Questions about calculating accuracy in training

### ISSUE THREAD

**Issue by plastictime** [qinnzou/DeepCrack#21]
In the paper, it is mentioned that adding a sigmoid to the feature map output by the network can convert the feature map into a crack prediction graph. Then I looked at the code. The calculation of loss uses BCEWithLogitsLoss, that is, the network output is added to the sigmoid operation and then calculated. The visualisation also puts the output after the sigmoid operation as a prediction graph. However, when the accuracy is calculated, the output of the network was not processed with sigmoid. What's the reason?

**Comment by qinnzou** [comment]
@plastictime We reorganized the codes after the publication of the paper. This may lead to the difference of the output. Did you compare the generated results with or without sigmoid ? This may be an interesting point. I think the output should be comply with the loss calculation process. Thanks
