### ISSUE TITLE
Test crack detection on my own images issue

### ISSUE THREAD

**Issue by ousim97** [qinnzou/DeepCrack#5]
Hello,

First, thank you for this very helpful code. Actually, I already developped a python script to detect road cracks using morphology methods, and I want to compare it with your method.

The issue when I launch the test.py script is as following: 
`  File "C:\Program Files (x86)\ia\DeepCrack-master\codes\data\dataset.py", line 33, in __call__
     if len(lab.shape) != 2:
AttributeError: 'NoneType' object has no attribute 'shape'`

How can I solve it please? 

If I want to test my own images, do I have to create my own val_example.txt (test_example.txt) with the name and the path to my test images? 

I want also to know if label images are necessary to test my own images.

Thanks in advance.

**Comment by GrisaiaTrigger** [comment]
Hello,
Did you solve this issue?  I meet the same error codes when I launch the test.py to detect my own crack images. Is it beacuse the image paths in val_example.txt (test_example.txt) are false or other reasons? Could you tell me how to solve it please? 
Thank you very much!
