### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ousim97** [qinnzou/DeepCrack#6]
Hi, 

I have an issue in the test.py code with the pretrained model. Everytime I run it I got the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 4.00 GiB total capacity; 2.48 GiB already allocated; 105.14 MiB free; 2.51 GiB reserved in total by PyTorch)`

Note that I have reduced the batch size as suggested in other topics but I still get the  same eroor. Do you have a solution please?

Thanks in advance

**Comment by qinnzou** [comment]
An nvidia 1060 or up gpu may satisfy the requirement.

**Comment by ake020675** [comment]
ME TOO. Seems 4GB is not enough cause the batchsize has been set to 1

**Comment by qinnzou** [comment]
large GPU memory is required.
