### ISSUE TITLE
questing about the 'deepcrack' result

### ISSUE THREAD

**Issue by smhotkdg** [qinnzou/DeepCrack#8]
If I set the ground-truth pixel of the crack to be thicker than 1px, can the crack detected in the test get 1px or more?

**Comment by qinnzou** [comment]
If you use the pretrained model, the test results will be one pixel wide.  If the crack ground truth are with width more than 1px, then you can trainyour own model with our codes. In such case, you can get results with larger crack width.

**Comment by qinnzou** [comment]
@prinzROSE training from scratch
